application: stripe-gae-frontend
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: website/css

- url: /js
  static_dir: website/js

- url: /img
  static_dir: website/img

- url: /.*
  script: _go_app
